Refactor terraform pieces for deploying osm-stats components to Azure
dakotabenjamin/osm-stats pull request #1
Opened 2021-11-30 13:00 UTC by eternaltyro

- Refactor terraform code to be compliant with v1.0.11
- Bump AzureRM and random provider versions
- Add lock files to gitignore
- Split the main terraform file into variable, provider and output files
- Fix database resource blocks to update deprecated code
- Use jsonencode for JSON components for better control and readability
- Use hotosm images instead of ARC images
- Use custom OVERPASS_URL value for envvars
- Update formatting and syntax throughout

TODO:

- Upgrade state file using terraform 0.13upgrade

2021-11-30 14:42 UTC, dakotabenjamin requested changes
I was able to run a terraform plan using v0.13. There are a few changes needed, but then let's discuss next steps.

2021-11-30 14:42 UTC, dakotabenjamin commented on deployment/osm-stats.tf
> -    image = "quay.io/americanredcross/osm-stats-api:v0.22.0"
This label should be kept

2021-11-30 14:42 UTC, dakotabenjamin commented on deployment/osm-stats.tf
> -    cpu = "3"
any particular reason to lower this value?

2021-11-30 15:25 UTC, eternaltyro commented
@dakotabenjamin made the reverts

2021-12-01 10:51 UTC, eternaltyro commented
@dakotabenjamin fixed a couple more lines for syntactic sugar.

2024-08-13 06:19 UTC, closed without merging